name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config liblzma-dev cmake make nettle-dev rustup

    - name: Setup Rust for root
      run: sudo rustup default stable

    - uses: actions/checkout@v2

    - name: Build # caches the build for test below
      run: sudo cargo build --verbose

    - name: Test
      run: sudo cargo test
